name: Build Spark OS for blossom

on:
  workflow_dispatch: # Manually trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 720 # 12 hours max build time

    steps:
    # Checkout your GitHub repo
    - name: Checkout
      uses: actions/checkout@v3

    # Set up environment
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl python3 openjdk-11-jdk ccache zip unzip \
          bc make repo libncurses5 python-is-python3 rsync

    # Initialize and sync Spark OS repo
    - name: Initialize and sync repo
      run: |
        mkdir spark && cd spark
        repo init --no-repo-verify -u https://github.com/Spark-Rom/manifest.git -b spark
        # Add your device tree using local_manifests
        git clone https://github.com/AsTechpro20/local_manifests_blossom.git -b lineage-20 .repo/local_manifests
        repo sync --force-sync -j$(nproc --all)

    # Fix device trees (rename lineage_* to spark_*)
    - name: Fix device trees
      run: |
        cd spark
        find device -type f -exec sed -i 's/lineage_/spark_/g' {} +
        find vendor -type f -exec sed -i 's/lineage_/spark_/g' {} +
        find . -type f -name "*lineage*.mk" -exec bash -c 'mv "$0" "${0//lineage_/spark_}"' {} \;

    # Build Spark OS
    - name: Build Spark OS
      run: |
        cd spark
        source build/envsetup.sh
        lunch spark_blossom-userdebug
        mka bacon | tee ../build.log

    # Upload ROM to Telegram
    - name: Upload ROM to Telegram
      run: |
        cd spark/out/target/product/blossom
        ROM_FILE=$(ls *.zip | head -n1)
        curl -F chat_id=1910625218 \
             -F document=@"$ROM_FILE" \
             -F caption="✅ Spark OS build completed successfully" \
             https://api.telegram.org/bot7863915048:AAG0PjWioCIeIlP9kDdvsTDkKfJ2J57dR-Q/sendDocument

        cd ../../../../..
        curl -F chat_id=1910625218 \
             -F document=@"build.log" \
             -F caption="📄 Spark OS build log" \
             https://api.telegram.org/bot7863915048:AAG0PjWioCIeIlP9kDdvsTDkKfJ2J57dR-Q/sendDocument
             
